# Generated by Django 4.0.4 on 2022-05-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(null=True, upload_to='attachments'),
        ),
    ]
