# Generated by Django 4.0.4 on 2022-05-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtasks', '0002_task_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments', verbose_name='attachment'),
        ),
    ]
