# Generated by Django 4.0.4 on 2022-05-22 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CBU', '0001_initial'),
        ('reports', '0002_report_cbu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='cbu',
        ),
        migrations.AddField(
            model_name='report',
            name='CBU',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CBU.cbu'),
        ),
    ]
