# Generated by Django 4.0.4 on 2022-05-22 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_report_cbu_report_cbu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.IntegerField(choices=[('10-green', 'Green'), ('20-yellow', 'Yellow'), ('20-red', 'Red'), ('00-completed', 'Completed')], default=0),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, max_length=200, verbose_name='stage')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('start', models.DateField()),
                ('finish', models.DateField()),
                ('complete', models.IntegerField(default=0, verbose_name='complete%')),
                ('status', models.CharField(choices=[(0, 'Draft'), (1, 'Publish'), (2, 'Delete')], default='10-green', max_length=20, verbose_name='status overall')),
                ('Report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
            },
        ),
    ]
