# Generated by Django 4.0.4 on 2022-05-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_status_b_report_status_o_report_status_s_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='no',
            field=models.SmallIntegerField(blank=True, default=1, verbose_name='No'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('10-green', 'Green'), ('20-yellow', 'Yellow'), ('20-red', 'Red'), ('90-completed', 'Completed'), ('00-notApplicable', 'N/A')], default='00-notApplicable', max_length=20, verbose_name='status overall'),
        ),
        migrations.AlterField(
            model_name='report',
            name='issue',
            field=models.TextField(verbose_name='Issues & Plan'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status_b',
            field=models.CharField(choices=[('10-green', 'Green'), ('20-yellow', 'Yellow'), ('20-red', 'Red'), ('90-completed', 'Completed'), ('00-notApplicable', 'N/A')], default='10-green', max_length=20, verbose_name='-budget'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status_o',
            field=models.CharField(choices=[('10-green', 'Green'), ('20-yellow', 'Yellow'), ('20-red', 'Red'), ('90-completed', 'Completed'), ('00-notApplicable', 'N/A')], default='10-green', max_length=20, verbose_name='status overall'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status_s',
            field=models.CharField(choices=[('10-green', 'Green'), ('20-yellow', 'Yellow'), ('20-red', 'Red'), ('90-completed', 'Completed'), ('00-notApplicable', 'N/A')], default='10-green', max_length=20, verbose_name='-scope'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status_t',
            field=models.CharField(choices=[('10-green', 'Green'), ('20-yellow', 'Yellow'), ('20-red', 'Red'), ('90-completed', 'Completed'), ('00-notApplicable', 'N/A')], default='10-green', max_length=20, verbose_name='-schedule'),
        ),
    ]
