# Generated by Django 4.0.4 on 2022-05-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_milestone_finish_alter_milestone_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='no',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='No'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
