# Generated by Django 4.0.4 on 2022-05-22 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WBS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wbs', models.CharField(db_index=True, max_length=10, verbose_name='WBS')),
                ('name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('cbu', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='CBU')),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Budget')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WBS',
                'verbose_name_plural': 'WBS',
            },
        ),
    ]
