# Generated by Django 4.0.4 on 2022-05-28 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_extenduser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_app_reviewer',
            field=models.BooleanField(default=False, verbose_name='App_Architect?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_external',
            field=models.BooleanField(default=False, verbose_name='External user?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_inf_reviewer',
            field=models.BooleanField(default=False, verbose_name='Infrastructure reviewer?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_mgt_reviewer',
            field=models.BooleanField(default=False, verbose_name='Management reviewer?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_pro_reviewer',
            field=models.BooleanField(default=False, verbose_name='Procurement reviewer?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_sec_reviewer',
            field=models.BooleanField(default=False, verbose_name='Security reviewer?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
        migrations.AddField(
            model_name='profile',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_to', to=settings.AUTH_USER_MODEL, verbose_name='manager'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('STAFF', 'STAFF'), ('USER', 'USER')], default='USER', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='u_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.dept', verbose_name='Dept'),
        ),
        migrations.AddField(
            model_name='profile',
            name='u_div',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.div', verbose_name='Div'),
        ),
        migrations.AddField(
            model_name='profile',
            name='u_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.team', verbose_name='Team'),
        ),
    ]
