# Generated by Django 4.0.4 on 2022-05-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_created_at_profile_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_psmadm',
            field=models.BooleanField(default=False, verbose_name='PSM Admin?'),
        ),
    ]
