# Generated by Django 4.0.4 on 2022-05-29 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_delete_extenduser'),
        ('users', '0006_remove_profile_role_profile_is_psmadm'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='CBU',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.cbu'),
        ),
    ]
