# Generated by Django 4.0.4 on 2022-05-22 07:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import psm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
        ('sap', '0001_initial'),
        ('CBU', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='check item...', max_length=200, verbose_name='name')),
                ('desc', models.CharField(blank=True, max_length=2000, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategy_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('type', models.CharField(choices=[('00-Major', 'Major'), ('10-Small', 'Small'), ('20-Enhancement', 'Enhancement'), ('30-Unclassifed', 'Unclassified')], default='30-Unclassifed', max_length=20, verbose_name='type')),
                ('year', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(2020), psm.models.max_value_current_year], verbose_name='Year')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='description')),
                ('status_o', models.CharField(choices=[('10-green', 'Green'), ('20-yellow', 'Yellow'), ('20-red', 'Red'), ('00-completed', 'Completed')], default='10-green', max_length=20, verbose_name='status overall')),
                ('status_t', models.CharField(choices=[('10-green', 'Green'), ('20-yellow', 'Yellow'), ('20-red', 'Red'), ('00-completed', 'Completed')], default='10-green', max_length=20, verbose_name='status schedule')),
                ('status_b', models.CharField(choices=[('10-green', 'Green'), ('20-yellow', 'Yellow'), ('20-red', 'Red'), ('00-completed', 'Completed')], default='10-green', max_length=20, verbose_name='status budget')),
                ('status_s', models.CharField(choices=[('10-green', 'Green'), ('20-yellow', 'Yellow'), ('20-red', 'Red'), ('00-completed', 'Completed')], default='10-green', max_length=20, verbose_name='status scope')),
                ('resolution', models.TextField(blank=True, max_length=2000, null=True, verbose_name='PM Memo')),
                ('state', models.CharField(choices=[('00-to-do', 'To Do'), ('10-in-progress', 'In Progress'), ('20-on-hold', 'Blocked'), ('30-done', 'Done'), ('40-cancel', 'Canceled')], default='00-to-do', max_length=20, verbose_name='state')),
                ('complete', models.IntegerField(default=0, verbose_name='complete%')),
                ('priority', models.CharField(choices=[('00-low', 'Low'), ('10-normal', 'Normal'), ('20-high', 'High'), ('30-critical', 'Critical')], default='10-normal', max_length=20, verbose_name='priority')),
                ('est_cost', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Est. cost')),
                ('app_budg', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Approved budget')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='deadline')),
                ('p_pre_planning', models.DateField(blank=True, null=True, verbose_name='planned pre-planning start')),
                ('p_kickoff', models.DateField(blank=True, null=True, verbose_name='planned kick-off date')),
                ('p_design_b', models.DateField(blank=True, null=True, verbose_name='planned design start')),
                ('p_design_e', models.DateField(blank=True, null=True, verbose_name='planned design end')),
                ('p_develop_b', models.DateField(blank=True, null=True, verbose_name='planned develop start')),
                ('p_develop_e', models.DateField(blank=True, null=True, verbose_name='planned develop end')),
                ('p_uat_b', models.DateField(blank=True, null=True, verbose_name='planned UAT start')),
                ('p_uat_e', models.DateField(blank=True, null=True, verbose_name='planned UAT end')),
                ('p_launch', models.DateField(blank=True, null=True, verbose_name='planned launch')),
                ('p_close', models.DateField(blank=True, null=True, verbose_name='planned closing')),
                ('a_pre_planning', models.DateField(blank=True, null=True, verbose_name='actual pre-planning start')),
                ('a_kickoff', models.DateField(blank=True, null=True, verbose_name='actual kick-off date')),
                ('a_design_b', models.DateField(blank=True, null=True, verbose_name='actual design start')),
                ('a_design_e', models.DateField(blank=True, null=True, verbose_name='actual design end')),
                ('a_develoa_b', models.DateField(blank=True, null=True, verbose_name='actual develop start')),
                ('a_develoa_e', models.DateField(blank=True, null=True, verbose_name='actual develop end')),
                ('a_uat_b', models.DateField(blank=True, null=True, verbose_name='actual UAT start')),
                ('a_uat_e', models.DateField(blank=True, null=True, verbose_name='actual UAT end')),
                ('a_launch', models.DateField(blank=True, null=True, verbose_name='actual launch')),
                ('a_close', models.DateField(blank=True, null=True, verbose_name='actual closing')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments', verbose_name='attachment')),
                ('CBU', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CBU.cbu')),
                ('CBUpm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbu_pm', to='common.extenduser', verbose_name='CBU PM')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prj_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.org')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='psm.strategy')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager', to=settings.AUTH_USER_MODEL, verbose_name='HAEA PM')),
                ('wbs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sap.wbs', verbose_name='WBS (SAP)')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('is_done', models.BooleanField(default=False, verbose_name='done?')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psm.project')),
                ('checkitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='psm.checkitem')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Check List',
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['state', 'CBU', '-priority', '-deadline'], name='mProjects_Project_priority_idx'),
        ),
    ]
