# Generated by Django 4.0.4 on 2022-05-23 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('psm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'verbose_name': 'Strategy', 'verbose_name_plural': 'Strategies'},
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('00-backlog', 'Backlog'), ('10-to-do', 'To Do'), ('20-doing', 'Doing'), ('30-on-hold', 'Blocked'), ('50-done', 'Done'), ('90-cancel', 'Canceled')], default='10-to-do', max_length=20, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status_b',
            field=models.CharField(choices=[('10-green', 'Good'), ('20-yellow', 'Issue'), ('20-red', 'Roadblock'), ('90-completed', 'Completed'), ('00-notApplicable', 'Not started')], default='10-green', max_length=20, verbose_name='status budget'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status_o',
            field=models.CharField(choices=[('10-green', 'Good'), ('20-yellow', 'Issue'), ('20-red', 'Roadblock'), ('90-completed', 'Completed'), ('00-notApplicable', 'Not started')], default='10-green', max_length=20, verbose_name='status overall'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status_s',
            field=models.CharField(choices=[('10-green', 'Good'), ('20-yellow', 'Issue'), ('20-red', 'Roadblock'), ('90-completed', 'Completed'), ('00-notApplicable', 'Not started')], default='10-green', max_length=20, verbose_name='status scope'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status_t',
            field=models.CharField(choices=[('10-green', 'Good'), ('20-yellow', 'Issue'), ('20-red', 'Roadblock'), ('90-completed', 'Completed'), ('00-notApplicable', 'Not started')], default='10-green', max_length=20, verbose_name='status schedule'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager', to='common.extenduser', verbose_name='HAEA PM'),
        ),
    ]
